import Head from 'next/head'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex justify-center flex-col gap-6 items-center w-[100vw] min-h-[100vh]'>
        <Link href={"/Login"}>Login</Link>
        <Link href={"/Register"}>Register</Link>
      </main>
    </>
  )
}
